using Tests.Runtime.Emit.Inline.Helpers;

namespace Tests.Runtime.Emit.Inline.Analyzer;

[TestClass]
public sealed class AnalyzerLifecycleTests
{
    [TestMethod]
    public async Task GeneratedSource_WithInvalidOperand_IsAnalyzedAndReported()
    {
        const string source = """
            // <auto-generated/>
            using Nebulae.Runtime.Emit.Inline;

            static class GeneratedExample
            {
                public static void Use(int value)
                {
                    IL.Emit.Ldc_I4(value);
                }
            }
            """;

        await AnalyzerTestHelpers.VerifyDiagnosticsAsync(
            [new AnalyzerTestSource(source, "GeneratedExample.g.cs")],
            includeInlineAssembly: true,
            AnalyzerTestHelpers.Diagnostic("NEBIL004", "value", 1) with
            {
                SourcePath = "GeneratedExample.g.cs",
                Message = "Operand for inline IL placeholder member 'Ldc_I4' must be a compile-time constant",
            });
    }

    [TestMethod]
    public async Task Diagnostic_FromMultipleSources_RetainsSourcePath()
    {
        const string validSource = """
            using Nebulae.Runtime.Emit.Inline;
            static class First { public static void Use() => IL.Emit.Ldc_I4(1); }
            """;
        const string invalidSource = """
            using Nebulae.Runtime.Emit.Inline;
            static class Second { public static void Use(int value) => IL.Emit.Ldc_I4(value); }
            """;

        await AnalyzerTestHelpers.VerifyDiagnosticsAsync(
            [
                new AnalyzerTestSource(validSource, "First.cs"),
                new AnalyzerTestSource(invalidSource, "Second.cs"),
            ],
            includeInlineAssembly: true,
            AnalyzerTestHelpers.Diagnostic("NEBIL004", "value", 1) with
            {
                SourcePath = "Second.cs",
                Message = "Operand for inline IL placeholder member 'Ldc_I4' must be a compile-time constant",
            });
    }

    [TestMethod]
    public async Task Compilation_WithoutInlineAssembly_ProducesNoAnalyzerDiagnostics()
    {
        const string source = """
            static class Example
            {
                public static int Add(int left, int right) => left + right;
            }
            """;

        await AnalyzerTestHelpers.VerifyNoDiagnosticsAsync(
            [new AnalyzerTestSource(source, "NoInlineAssembly.cs")],
            includeInlineAssembly: false);
    }
}
