<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<CICD>none</CICD>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<DebugType>pdbonly</DebugType>
		<DebugSymbols>true</DebugSymbols>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
		<PackageReference Include="Nebulae.Runtime.Emit.Inline" Version="2.0.0" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Nebulae.Diagnostics\Nebulae.Diagnostics.csproj" />
		<ProjectReference Include="..\..\src\Nebulae.Lifetime.WeakEvents\Nebulae.Lifetime.WeakEvents.csproj" />
		<ProjectReference Include="..\..\src\Nebulae.Reflection\Nebulae.Reflection.csproj" />
		<!--
		<ProjectReference Include="..\..\src\Nebulae.Runtime.Emit.Inline\Nebulae.Runtime.Emit.Inline.csproj" />
		<ProjectReference Include="..\..\src\Nebulae.Runtime.Emit.Inline.MSBuild\Nebulae.Runtime.Emit.Inline.MSBuild.csproj" ReferenceOutputAssembly="false" />
		<ProjectReference Include="..\..\src\Nebulae.Runtime.Emit.Inline.Analyzers\Nebulae.Runtime.Emit.Inline.Analyzers.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		-->
	</ItemGroup>

</Project>
