<Project Sdk="MSTest.Sdk/4.0.2">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<CICD>inline-il-package</CICD>
		<CICDOperatingSystems>linux;windows</CICDOperatingSystems>
		<CICDConfigurations>Debug;Release</CICDConfigurations>
		<CICDStage>source</CICDStage>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EnableMicrosoftTestingExtensionsCodeCoverage>false</EnableMicrosoftTestingExtensionsCodeCoverage>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Build.Framework" Version="18.7.1" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.7.1" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0" PrivateAssets="all" />
		<PackageReference Include="Mono.Cecil" Version="0.11.6" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Tests.Runtime.Emit.Inline.Infrastructure\Tests.Runtime.Emit.Inline.Infrastructure.csproj" />
		<ProjectReference Include="..\..\src\Nebulae.Runtime.Emit.Inline\Nebulae.Runtime.Emit.Inline.csproj" />
	</ItemGroup>

</Project>
