<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net10.0</TargetFrameworks>
	</PropertyGroup>

	<Import Project="..\..\Nebulae.Reflection\Nebulae.Reflection.projitems" Label="Shared" />
	<Import Project="..\..\System.Diagnostics.CodeAnalysis\System.Diagnostics.CodeAnalysis.projitems" Label="Shared" />
	<Import Project="..\..\System.Runtime.CompilerServices\System.Runtime.CompilerServices.projitems" Label="Shared" />

	<ItemGroup>
		<PackageReference Include="Nebulae.Runtime.Emit.Inline" Version="2.0.0" PrivateAssets="all" />
		<PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0"  Condition=" $(TargetFramework) == 'netstandard2.0' " />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Nebulae.Diagnostics\Nebulae.Diagnostics.csproj" />
	</ItemGroup>

</Project>
