//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebulae.Runtime.Emit.Inline.Analyzers.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nebulae.Runtime.Emit.Inline.Analyzers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder members must be direct calls in an executable method body. 的本地化字符串。
        /// </summary>
        internal static string InvalidContextDescription {
            get {
                return ResourceManager.GetString("InvalidContextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inline IL placeholder member &apos;{0}&apos; cannot be used as a method group, in an expression tree, or outside an executable method body 的本地化字符串。
        /// </summary>
        internal static string InvalidContextMessage {
            get {
                return ResourceManager.GetString("InvalidContextMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inline IL placeholder member is used in an unsupported context 的本地化字符串。
        /// </summary>
        internal static string InvalidContextTitle {
            get {
                return ResourceManager.GetString("InvalidContextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Types from the inline IL placeholder assembly cannot occur in declarations or local storage. 的本地化字符串。
        /// </summary>
        internal static string PlaceholderTypeDescription {
            get {
                return ResourceManager.GetString("PlaceholderTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; stores or exposes inline IL placeholder type &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string PlaceholderTypeMessage {
            get {
                return ResourceManager.GetString("PlaceholderTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inline IL placeholder type cannot be stored or exposed 的本地化字符串。
        /// </summary>
        internal static string PlaceholderTypeTitle {
            get {
                return ResourceManager.GetString("PlaceholderTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Values produced by the inline IL reference API are compile-time placeholders and cannot be stored, returned, or passed to ordinary code. 的本地化字符串。
        /// </summary>
        internal static string ReferenceEscapeDescription {
            get {
                return ResourceManager.GetString("ReferenceEscapeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference placeholder must be consumed directly by an inline IL placeholder 的本地化字符串。
        /// </summary>
        internal static string ReferenceEscapeMessage {
            get {
                return ResourceManager.GetString("ReferenceEscapeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inline IL reference value escapes its placeholder expression 的本地化字符串。
        /// </summary>
        internal static string ReferenceEscapeTitle {
            get {
                return ResourceManager.GetString("ReferenceEscapeTitle", resourceCulture);
            }
        }
    }
}
